name: codemetrics
version: 1.0.0-alpha+1
author: Daniel Varga-Hali <dvargahali@gmail.com>
homepage: https://github.com/daniel-v/codemetrics.git
documentation: https://github.com/daniel-v/codemetrics.git
description: >
  Codemetrics for Dart is a simple command line utility that provides some
  insight into the "quality" of code.
dependencies:
  analyzer: ^0.36.3
  built_collection: ^4.2.2
  glob: ^1.1.7
  path: ^1.6.2
  html: ^0.14.0+2
  args: ^1.5.1
  resource: ^2.1.5
dev_dependencies:
  test: any
  mockito: any

environment:
  sdk: ">=2.6.0 <3.0.0"

executables:
  dart-codemetrics: codemetrics
